apiVersion: v1
kind: Service
metadata:
  name: jupyterlab
  labels:
    app: jupyterlab
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: jupyterlab