apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-runner
  labels:
    app: agent-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-runner
subjects:
- kind: ServiceAccount
  name: agent-runner
