apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jupyterlab-ccc
  labels:
    app: jupyterlab-ccc
spec:
  selector:
    matchLabels:
      app: jupyterlab-ccc
  template:
    metadata:
      labels:
        app: jupyterlab-ccc
    spec:
      containers:
      - image: gcr.io/deeplearning-platform-release/base-cpu:latest
        imagePullPolicy: Always
        name: jupyterlab-ccc
        ports:
        - containerPort: 8080
      serviceAccountName: default
